### ISSUE TITLE
Merging dataset with Backstabber's Knife Collection

### ISSUE THREAD

**Issue by piergiorgioladisa** [lxyeternal/pypi_malregistry#1]
Hi @lxyeternal! 

first of all congrats for the really nice work of your paper. 
I couldn't find an email to contact you so I decided to create this issue
I wanted to ask if it was OK for you to include this dataset in Backstabber's Knife Collection and thus merge the two datasets. I think it is really important for the scientific community to keep one updated dataset!
Looking forward for your response!

Cheers!

**Comment by lxyeternal** [comment]
Of course, it is my pleasure, but I hope to declare my paper for better reference by researchers.
ASE 2023 "An Empirical Study of Malicious Code In PyPI Ecosystem"
